### ISSUE TITLE
TextConverter should use FromDatabase() not From()

### ISSUE THREAD

**Issue by andresharpe** [NoxOrg/Nox.Generator#441]
Should we not use FromDatabase() here? Will perform better and Text is used a lot.

https://github.com/NoxOrg/Nox.Generator/blob/8b917af6b33da960f848251f7815434ea50f30e4/src/Nox.Types.EntityFramework/Types/Text/TextConverter.cs#L6

**Comment by rochar** [comment]
yes, still not migrated
