### ISSUE TITLE
[Nox.Generator] Generate navigation property in foreign entity for key relationship

### ISSUE THREAD

**Issue by ILoveMyTortoise** [NoxOrg/Nox.Generator#540]
one side:
name: TenantWorkplaceAddress

keys:
  - name: TenantWorkplaceId
    type: entity
    entityTypeOptions:
      entity: TenantWorkplace
    isRequired: true

other side:
name: TenantWorkplace

On TenantWorkplace side we need to generate a navigation property to a List<TenantWorkplaceAddress>? (zeroOrMany)

**Comment by rochar** [comment]
@anna-naumova25  can y review this logged by @ILoveMyTortoise , I think this is no longer a issue

If nothing to be done please close the ticket, otherwise lets do it
