### ISSUE TITLE
[Nox.Generators] Post/Put/Patch To Owned Entity in Parent Entity Odata Controller (Many)

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox.Generator#568]
Investigate the best practice for this, should the Create<EntityDto> receive single/List of key(s) to the related entity?

For now let's supports single key for related entities

**Comment by anna-naumova25** [comment]
Both approaches **List of Ids** and **List of Entities** are valid and can be considered as best practice for models with the relationships. What we should think about:
- using List of Ids is a lightweight solution however only existing entities can be linked to a parent model
- using List of Entities - can link existing children, create and update children entities. Need to discuss if we need this functionality.

@rochar let's discuss on Monday

**Comment by rochar** [comment]
in the scope of this ticket lets do:

1. the post of the parent entity with a single owned entity
2. 1. the post of the parent entity with a multiple owned entity
3.  the Post for an owned entity, meaning the parent entity already exists, example:
Example 

POST http://localhost:5000/odata/Employees(4)/Peers

public ActionResult PostToPeers([FromRoute] int key, [FromBody] Employee peer)

The same applies to Patch and Put

We should document this in our readme and define the workflow for delete a owned entity
