### ISSUE TITLE
[Nox.Generators] Create a new Entity and related entity in the same Post

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox.Generator#570]
relates #776 
### Create a new Entity and related entity in the same Post
1. Post allows to create and associate a related entity via navigation property 
   1. CreatedDto.template changes 
        2. Remove the Id Property for single entity
        3. Add the navigation property to <RelatedEntity>CreateDto with the name of the Relation
        Example:
        ```
        public virtual StoreOwnerCreateDto? Ownership { get; set; } = null!;
        ```
   1. Update factory to create related entity (using the related entity factory)
   5. Create a virtual method CreateRefTo\<EntityName\>(relatedKey) in the entity. Call it from the factory
1.  (**Pending**) If relation is one* and the related entity already exists how to associate it? Need an example where this makes sense

Example:

```
public abstract class StoreFactoryBase: IEntityFactory<Store,StoreCreateDto>
{

 private ClientApi.Domain.Store ToEntity(StoreCreateDto createDto)
 {
     var entity = new ClientApi.Domain.Store();
     entity.Name = ClientApi.Domain.Store.CreateName(createDto.Name);
		entity.EnsureId();
     var store = StoreOwnerFactory.CreateEntity(createDto.StoreOwner);
     entity.CreateRefToStoreOwner(store);
     return entity;
 }
...
}

public partial class Store : AuditableEntityBase, IEntityConcurrent
{
    public virtual void CreateRefToStoreOwner(StoreOwner storeOwner)
    {
        Ownership = storeOwner;
        //override business logic
    })
...
}
```

**Comment by anna-naumova25** [comment]
https://learn.microsoft.com/en-us/odata/webapi-8/fundamentals/ref-routing?tabs=net60%2Cvisual-studio
Based on Odata documentation there will be implemented POST, PUT and DELETE endpoints for the related entities (single and multiple)

TBD (@rochar, @ILoveMyTortoise)

1. Will we implement GET as per documentation above or will we use filtering as for owned relationships? If so we need to add AutoExpand for it.
2. Will we support the scenario when POST/PUT/PATCH to main entity contains related entity (single or list) to cover ExactlyOne and OneToMany relationships? If so need to discuss the DTO model (same as for Owned)
3. As per Odata documentation, PATCH method won't be implemented for this type of relationships. 
 
Draft PR is created for this ticket  - https://github.com/NoxOrg/Nox.Generator/pull/685
